language: node_js
node_js: node
jobs:
  include:
    - stage: install
      script: npm install
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test:ci
    - stage: build
      script: npm run build
